### ISSUE TITLE
Get external IP in parallel

### ISSUE THREAD

**Issue by andresgongora** [andresgongora/scripts#35]
This is just an idea, but how about this:

1. Check what tools the user has to get her external IP
2. (somehow) call them all in parallel
3. Use the first one to finish

**Comment by olmari** [comment]
There are 2 sides to this kind of behaviour. It could make overall startup faster, which is desirable, but it will also use machine resources kind on unneccesarily. I suspect only place where this would benefit the most is when one (or more) methods won't work for any reason, thus trying things in parallel would (maybe) make one of the things work...

While starting subcommands in paraller is easy enough, plenty methods listed in https://www.slashroot.in/how-run-multiple-commands-parallel-linux but I have yet to figure out how can we then properly (so they will not mix the first result in any way after they finished) "forget" the yet unfinished scripts so that they do what they do and we don't care anymore, and stiill be able to use the first result that came out from any of the subcommands.

**Comment by andresgongora** [comment]
You are right. It might not even improve by that much. I'm moving this to #46 and closing this issue.
