### ISSUE TITLE
Limit CPU % to 100 and make it a bit faster

### ISSUE THREAD

**Issue by andresgongora** [andresgongora/scripts#73]
Currently, the CPU percentage is shown as the average of the last minute. This is meant to avoid showing the spike of loading up a terminal and such. I suggest the following changes:

- [ ] Get CPU usage % as the average of the last 10 or so seconds. Ideally, make this user configurable.
- [x] Compute CPU % in the range [0-100]. Right now, if you have 8 cores, the range would be 0-800.

But beware of breaking `CPU_CRIT` alarm. With 8 cores, if one of them is at 100% because some program is doing nasty stuff, but the rest is idle, the average load would still seem to be below 13%. This requires to think everything through.

Maybe replace the bar all together with something different?? (it must still fit in a single line)

**Comment by olmari** [comment]
Tresholding this kind of values is always things where is no correct answers.

For the latter bullet-point, calculation currently calculates exactly average for all the cores in system, like you do describe it there later.

I think instead of representing the number as actual percent-figure we could just show the load-figure, which describes things more accurately as load of 8.00 in an 8 core system would mean that demand fromCPU's are exactly 1 for each core. Load can be higher than amount of cores, it just means that demand is higher than there is capable processing power.

The graph-bar itself could still stay exactly the same, it would show roughly in percentage that what average use there is from all the cores.. So we would get best of both worlds: bar-graph showing quickly the average load on whole system and then numbers would tell the actual load... maybe combine the nu,ber with available cores (we already get that info on the code) and show it like "0.13 / 8".

Other than that it is matter of personal preferences.. for some, load of under maximum is failure (say mining).. And after all load is still an number, users needs gives it an meaning.

**Comment by andresgongora** [comment]
I liek your suggestion. We show the bar as as a percentage indicator of system load, but do not show a % next to it, rather a system load in the shape 1.3 / 8. Which is also aesthetically more in line with the RAM, SWAP, etc...

**Comment by andresgongora** [comment]
Now the CPU load monitor is configurable. However, the average is still for the last 60 seconds, instead the last 5-10 seconds. I don't know how to configure this, but I think its not as critical as displaying the value properly. Will be addressed when new branch `features/cleanup_startup` gets merged.
