### ISSUE TITLE
Now load avg is % again?

### ISSUE THREAD

**Issue by olmari** [andresgongora/scripts#90]
Where did the actual load-figure went? :P At least develop branch is now not curent vompared to master :)

**Comment by andresgongora** [comment]
Which load figure? :S I'm confused. SHould I have had a conflict when pushing the last conflict?
This morning I pushed v1.4+1.4.1 (some fixes), and since them everything has gone to develop.

I did some quick test and could choose between % and CPU load. Please elaborate and I'll try to revert it if I broke something :)

**Comment by andresgongora** [comment]
Ahh, you mean, by default?? WHether load avg is % by default?
That can be changed real quick. I probably forgot it from my tests and left it as %

**Comment by olmari** [comment]
Master shows load avg as X/Y, develop shows N%

**Comment by andresgongora** [comment]
By default? Ok. I'm changng it to X/Y in develop, and merge it as v1.4.2 (some bugs were fixed, so its a good idea)

**Comment by andresgongora** [comment]
Default values fixed and merged into `master` :D
